version: '3.8'

services:
  docgpt:
    build: .
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - ./backend/media:/app/media
      - ./backend/chroma_db:/app/chroma_db
      - ollama_data:/root/.ollama
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
